/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sequality;

public class App {
  public String getGreeting() {
    return "Hello World!\nSum of 2 and 3 is 5. Average is 2.5.\nSum of 1 to 10 is 55. Average is 22.5.\nSum of odd of 1 to 10 is 25. Sum of even is 30.";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
  }
}
