/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sequality;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
  @Test
  public void testAppHasAGreeting() {
    App classUnderTest = new App();
    assertNotNull("app should have a greeting", classUnderTest.getGreeting());
  }

  @Test
  public void testAppReternHelloWorld() {
    App classUnderTest = new App();
    assertEquals(
        "Hello World!\nSum of 2 and 3 is 5. Average is 2.5.\nSum of 1 to 10 is 55. Average is 22.5.\nSum of odd of 1 to 10 is 25. Sum of even is 30.",
        classUnderTest.getGreeting());
  }
}
